language: python
python:
- '2.7'
- '3.7'
install:
- pip install -e .[test]
script:
- python setup.py test
env: 
before_install:
- openssl aes-256-cbc -K $encrypted_304b46f04559_key -iv $encrypted_304b46f04559_iv
  -in id_rsa.enc -out /tmp/id_rsa -d
