language: python
python:
  - "2.7"
  - "3.7"

install:
    - pip install -e . 
script:
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then (wizard --branch $TRAVIS_PULL_REQUEST_BRANCH --test --debug 2); fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then (wizard --branch $TRAVIS_BRANCH --test --debug 2); fi'
