language: python
python:
- '2.7'
- '3.7'
install:
- pip install -e .[test]
script:
- python setup.py test
env:
  global:
    secure: F5LSHGB2aECoLvkBx3b5yahHPAtw6sRETB0mvthkftV6LVtWLCJ3qV2YT6iAWkmy3KqLt1z5LSdVfYR++fi4z3qPYtMGxBQ7rSNldDMj/4NCg1G5s2JvUcPDU8l3EcAIOVQjnA/efraN0Bu66847lftseI+JdhjAEeYbP46/jIrFsFdt+lDzjt1MlQX92eX1DHk9d1srma2iwKr7+osQ8ALcpwdg/go7fIk5yWnBzLihJ7voEvr7qz/vgswKI36uNHzwailcynOcEb4mSAjbCGNLfKDUljBB2yUQAKZ2pZ3LGpD1UdRkqsNOFJJELUCYihrv/2GUsGI8QJNSoy3XIQjjVlRc+CE0YFq6X1r089InSHVP1GW3A/qFj/3SFzKj5lc7yJfZZsoDSofmf9cLz0+WtA32bttS0Ns0029X6F4njp4ZSMtCc7FB7KzpoFb3fBGafNEoeeg6525pCA9eDCg+Pr+fD1IXfvD7FLOLh81DZT53yRu3Yb8D16f4kNNGUor0adv0zXEhJD6VSgfq7Xx4qIMdwUsYBZ/DMndKmaotUTkeq4NK6JCn+eMwhZc0p+T2cjzSlBDURCGntoXvXlraNr2zMxT3fsQO9PXKaPyQWP2eT+zOqHeZf3zP4amrRDZA0RF/cf0l0KWaAIEeCXnzODydHuWEx5ldM8yn3Fw=
before_install:
- openssl aes-256-cbc -K $encrypted_304b46f04559_key -iv $encrypted_304b46f04559_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
