language: python
python:
- '2.7'
- '3.7'
install:
- pip install -e .[test]
script:
- python setup.py test

env:
  global:
    secure: gwlwI9JIlLmEYgAze5tlQRYcwkijRPue/thHJkhpMGTx8lrDQPuP5/8O4trYTTwqEcxq27/R5foKaMSwWW+DVFg/COBOnnSUcovduXK3JVXlMv/fdpUxUGrzUNnegfKQ6f6kTQ5cXYYBb8be7Sxt9TjepG7L4epvcJ2cwaUkW1w3jNFqBpRwm7Wz7QxKmWdgNZku7vG76Ken0CBpCnAXUp4hIGw+Izzkfo/YL4QLgHL44Dj7zo+xCFNqok/MTW+oVTRBbe9fseypSc3nRTxbcbxHomv4AtrerXCxFpG7aLEEKVmd49v9pSgsSnrW/rVvyK12emVdfOi8VukQv1GZc+w9qg61Ji11gxEBEu7oan3/O86lwNQ5Oa77d+Ic6RBAlBwoBmMRI9Z5j+YjAqzPGTqCLpuLt6wLlqeLAM+QoXXJK19PJqJfgfekikSvXtU5B3JnBWx0K/Xm+BXIUveBxdaw9YCBhEQFSa55ex610tQu5ga+V/CORDmi95f4a4rOpkS4cB0br4F8s4eAEsnAbZxJCv7hEQhaAh/OrL3HtWtKytiuB3xn0Z6wZI8uTz6caNK0VEVxL/vVNe0sOLHbpd7Of9ghrtlstdOq+eMedCz6rsgK05d7W4QqHvAkDIvuI8FiU6l0G1di4RlrXrrZVRUajDnhoRva/bsSi+3Tcvk=
