language: python
python:
- '2.7'
- '3.7'
install:
- pip install -e .[test]
script:
- python setup.py test
env:
  global:
  - secure: Hhz/FcPN705LIRYm0fDCnr4l2pUl7uIhC5cChJUm2Rmjs7jaydNYfVdqtxxMeHerA7edErvcrPD/Xt8EQWrvexwxJs6G0+pvXITk1v0kDF71yCMm526tOI+HYNL7hPdWgCqeoDtcWp6B1M/dXvbjt6vCejhMFo9uidYfqvPW8JeMBYAgfvFcxsHz1J47K9M4gK3apCsdyccrUuMxBsMhzjwDdW3dlgNzZwYiyv//34JQj6U/Q9rXo3l3/evDln6pYA8MvkEfTsGG3QfsMl/KiqXwmyR+Zep9ntrgMr/pLBLLL5S8w47tOuOghplX/dHnfUIPEzYHDm/Qe+xDURdN8VTTFaDSrtQHc8Y84KFU/PckjFxoF2MMQVe06wbqxTZLKE4LecIJM+fDn0F70IQUY8M/rfLBsRL1FVKdDU6Tl+OMV/hIUM0dhnr1Oidly3r9g1u1+YFqFq3gg3imKr55DbMI8um5tPFCPPsiCrRAOTo3nyg8m8TjiW+ttA3RyxUfhGw9uyu5Tr10GfwRvsnyxuD8v02aOq1yshAA8m8apmXvM13KKvKRoVcPsRVRfFGKX6TuB7VlRrtCQwYSWPM2SyTGS3dC9Un7ea0nradsIhN+uxLr5OpB4OUxMWSahVD1+WXY3+F3cw3niX003qV2Ks9PPd2HeMV8ShxLpH7RqxY=
  - secure: czSs3xvMj4oo+osLHujV8mlplV4nvCABHpsG+3ja6orXvSbNUuQqjlDoJrDlM346BhpuLzEkfJ/h1Vbcb2LmB0hKIZc5LkJWN3bsFCU6QyIIobVYX8yZGYSXlWg9PVinrKGz9wAIyg1VSCwNwLFv0+pJIhR/2WWflmTUAzKpYR1Q2flB3DeuuSDJ12nNAYFPXXszGgbV3xpJsa/FBX1TQ+6ngkNOrOUIIxusErpns6I+QROSg9g+l1UTcEhRiMr+rY6YP1wS6T1LWb4DCPTZ3N135BhTF+Vf0PGKpBuV9yE5vPdv8yZ/pptjsDGkV+ndJ9P8T9g+YZi/Xj/dEEYBFnjWFaB4RQf9ZSs+amF9HSgeTmabYDnNOAe1wMEZpi6xuPnXee2BEKsmWIerRWA/gzYKrYQuF+pAtk7jEm4qprlD2ZVFVP0a2AfJ+dSod/RZx4OiQ1we9FaEQinqLB7z7Jaz/R1nS4ieqDzwwyFQSLmu2U5OfmpKE0lWGLlHpoImU/SIhgQer9Af1IQOT0GSkrlvY02Z8eaWNAwo/8xrm6aduSRaxHkZdBrHgawgrVRPrKVBqu7rwyIBzMPPZkQF1lMilg+cfojn4Mu+bLMxYrFTRAbmY8TNJdmpjZ9hLJFgEP0o86Wy+mkhiqfFNwWP7rdNc4+CKW9WwfGKNROtPxU=
